---
title: "Marketing_Analytics_HW1"
author: "Hayrapetyan Nane"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(readxl)
library(ggplot2)
library(ggpubr)
library(knitr)
library(diffusion)
```

```{r}
data <- read_excel("stroller data.xlsx", sheet = 2)
data_stroller<- data[3:13, ]
colnames(data_stroller) <- c("Year", "Car Seats", "Carriages")
data_stroller$Year <- as.integer(data_stroller$Year)
data_stroller$Carriages <- as.integer(data_stroller$Carriages)
data_stroller
```


```{r}
#Visualizing the dataset
ggplot(data = data_stroller, aes(x = Year, y = Carriages)) + geom_bar(stat = 'identity')+
  labs(title = 'Baby Carriage sales in Germany, in 1000 units', x= ' ', y = 'Sales')+
  scale_x_continuous(breaks = 2014:2024, labels = 2014:2024)+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
#Defining F(x) and f(x)
bass.f <- function(t,p,q){((p+q)^2/p)*exp(-(p+q)*t)/(1+(q/p)*exp(-(p+q)*t))^2}

bass.F <- function(t,p,q){(1-exp(-(p+q)*t))/(1+(q/p)*exp(-(p+q)*t))
}
```

```{r}
#3
sales = data_stroller$Carriages
t = 1:length(sales)
bass_m = nls(sales ~ m*(((p+q)^2/p)*exp(-(p+q)*t))/
               (1+(q/p)*exp(-(p+q)*t))^2,
              start=c(list(m=sum(sales),p=0.02,q=0.4)))

summary(bass_m)

#Parameter estimations result to m=13770, p= 0.05371, q=0.09625

```

```{r}
time_ad <- ggplot(data.frame(t = c(1:11)), aes(t)) +
  stat_function(fun = bass.f, args = c(p=0.053716, q=0.09625)) +
  labs(title = 'f(t)')

carriage_sales <- ggplot(data = data_stroller, aes(x = Year, y = Carriages)) +
  geom_bar(stat = 'identity') + labs(x = " ", y = "Sales")

ggarrange(time_ad, carriage_sales)
```
```{r}
#7
data_stroller$pred_sales = bass.f(1:11, p = 0.053716, q =0.09625)*13770
ggplot(data = data_stroller, aes(x = Year, y = Carriages)) +
  geom_bar(stat = 'identity') +
  geom_point(mapping = aes(x=Year, y=pred_sales), color = 'red')+
  labs(title = "Bass Model Prediction vs Actual number of Sales of
       Carriages", x= ' ', y = 'sales')+scale_x_continuous(breaks = 2014:2024, 
                                                           labels = 2014:2024)
  
```
```{r}
#5
sales_vector <- as.numeric(data_stroller$Carriages)
diff_m = diffusion(sales_vector)
p=round(diff_m$w,4)[1]
q=round(diff_m$w,4)[2]
m=round(diff_m$w,4)[3]
diff_m

```
